### POST /register
POST http://localhost:3000/register
Content-Type: application/json

{
  "email" : "bill@msft.com",
  "password" : "1234"
}

### POST /login
POST http://localhost:3000/login
Content-Type: application/json

{
  "email" : "bill@msft.com",
  "password" : "1234"
}

### POST /login BAD
POST http://localhost:3000/login
Content-Type: application/json

{
  "email" : "bill@msft.com",
  "password" : "4321"
}
